name: colog_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - a5-miseq=20160825=hdfd78af_2
  - alsa-lib=1.2.14=hb9d3cd8_0
  - amply=0.1.6=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - archspec=0.2.5=pyhd8ed1ab_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.3.0=pyh71513ae_0
  - bcftools=1.22=h3a4d415_1
  - bedtools=2.31.1=h13024bc_3
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - biopython=1.85=py311h49ec1c0_2
  - blast-legacy=2.2.26=hf7ff83a_5
  - boltons=25.0.0=pyhd8ed1ab_0
  - boost-cpp=1.85.0=h3c6214e_4
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py311h1ddb823_4
  - bwa=0.7.19=h577a1d6_1
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py311h5b438cf_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - coin-or-cbc=2.10.12=h4d16d09_4
  - coin-or-cgl=0.60.9=hc46dffc_6
  - coin-or-clp=1.17.10=hc03379b_3
  - coin-or-osi=0.108.11=hf4fecb4_7
  - coin-or-utils=2.11.12=hc93afbd_6
  - coincbc=2.10.12=4_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.7.0=py311h38be061_0
  - conda-libmamba-solver=25.4.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - constellations=0.1.12=pyh7cba7a3_0
  - contourpy=1.3.3=py311hdf67eae_2
  - cpp-expected=1.1.0=hff21bea_1
  - curl=8.14.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - datamash=1.9=hb9d3cd8_0
  - datrie=0.8.3=py311h49ec1c0_0
  - dbus=1.16.2=h3c4dab8_0
  - distro=1.9.0=pyhd8ed1ab_1
  - docutils=0.22=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - dpath=2.2.0=pyha770c72_0
  - ea-utils=1.1.2.537=0
  - fmt=11.2.0=h07f6e7f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.2=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozendict=2.4.6=py311h49ec1c0_1
  - gatk=3.8=hdfd78af_12
  - gatk4=4.3.0.0=py36hdfd78af_0
  - gawk=5.3.1=hcd3d067_0
  - gcc_impl_linux-64=15.1.0=h4393ad2_5
  - gfortran_impl_linux-64=15.1.0=h3b9cdf2_5
  - giflib=5.2.2=hd590300_0
  - git=2.49.0=pl5321hc2ff736_2
  - git-lfs=3.7.0=h59e48b9_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.9=h86084c0_1
  - gofasta=1.2.3=h9ee0642_0
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.1.0=h6a1bac1_5
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.4.5=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.22.1=h566b1c6_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - igvtools=2.3.93=0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - isa-l=2.31.1=hb9d3cd8_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py311h38be061_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libarchive=3.8.1=gpl_h98cc613_100
  - libasprintf=0.25.1=h3f43e3d_1
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libboost=1.85.0=h0ccab89_4
  - libboost-devel=1.85.0=h00ab1b0_4
  - libboost-headers=1.85.0=ha770c72_4
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=35_h0358290_openblas
  - libcbor=0.10.2=hcb278e6_0
  - libclang-cpp20.1=20.1.8=default_h99862b1_1
  - libclang13=21.1.0=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfido2=1.16.0=h5da5774_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-devel_linux-64=15.1.0=h4c094af_105
  - libgcc-ng=15.1.0=h69a702a_5
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.3=hf39c6af_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_5
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=35_h47877c9_openblas
  - liblapacke=3.9.0=35_h6ae95b6_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmamba=2.3.2=hae34dd5_0
  - libmambapy=2.3.2=py311hd8214db_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenssl-static=3.5.3=hb03c661_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_2
  - libprotobuf=4.25.3=hd5b35b9_1
  - libsanitizer=15.1.0=h97b714f_5
  - libsolv=0.7.35=h9463b59_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_105
  - libstdcxx-ng=15.1.0=h4852527_5
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtiff=4.7.0=h8261f1e_6
  - libudev1=257.9=h085a93f_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.1=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mafft=7.526=h4bc722e_0
  - make=4.4.1=hb9d3cd8_2
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - matplotlib=3.10.5=py311h38be061_0
  - matplotlib-base=3.10.5=py311h0f3be63_0
  - menuinst=2.3.1=py311h38be061_1
  - minimap2=2.30=h577a1d6_0
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0=openmpi
  - mummer=3.23=pl5321h503566f_21
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-connector-c=6.1.11=h659d440_1008
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.10.1=h4a9d5aa_0
  - networkx=3.5=pyhe01879c_0
  - nextclade=3.16.0=h9ee0642_0
  - nlohmann_json=3.11.3=he02047a_1
  - numpy=1.26.4=py311h64a7726_0
  - openjdk=8.0.412=h2b85faf_2
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openmpi=4.1.6=hc5af2df_101
  - openssh=10.0p1=hc830a30_0
  - openssl=3.5.3=h26f9b46_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py311hed34c8f_0
  - pango=1.56.4=hadf4263_0
  - pangolin=4.3.1=pyhdfd78af_0
  - pangolin-data=1.35=pyh7e72e81_0
  - pcre2=10.45=hc749103_0
  - perl=5.32.1=7_hd590300_perl5
  - pillow=11.3.0=py311h3df08e7_2
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plac=1.4.5=pyhd8ed1ab_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - protobuf=4.25.3=py311hbffca5d_1
  - psutil=7.0.0=py311h49ec1c0_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulp=2.7.0=py311h38be061_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h49ec1c0_3
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.4=pyhcf101f3_0
  - pysam=0.23.3=py311hb456a96_1
  - pyside6=6.9.2=py311h72d58bf_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.13=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h2dc5d0c_2
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.2=h3fc9a0a_0
  - r-base=4.4.3=h85845a0_2
  - r-bitops=1.0_9=r44h54b55ab_1
  - r-catools=1.18.3=r44h3697838_1
  - r-cli=3.6.5=r44h3697838_1
  - r-colorspace=2.1_1=r44h54b55ab_1
  - r-farver=2.1.2=r44h3697838_2
  - r-ggplot2=4.0.0=r44h785f33e_0
  - r-glue=1.8.0=r44h54b55ab_1
  - r-gplots=3.2.0=r44hc72bb7e_1
  - r-gsalib=2.2.1=r44hc72bb7e_3
  - r-gtable=0.3.6=r44hc72bb7e_1
  - r-gtools=3.9.5=r44h54b55ab_2
  - r-isoband=0.2.7=r44h3697838_4
  - r-kernsmooth=2.23_26=r44ha0a88a1_1
  - r-labeling=0.4.3=r44hc72bb7e_2
  - r-lifecycle=1.0.4=r44hc72bb7e_2
  - r-munsell=0.5.1=r44hc72bb7e_2
  - r-plyr=1.8.9=r44h3697838_3
  - r-r6=2.6.1=r44hc72bb7e_1
  - r-rcolorbrewer=1.1_3=r44h785f33e_4
  - r-rcpp=1.1.0=r44h3697838_1
  - r-reshape=0.8.10=r44hc72bb7e_1
  - r-rlang=1.1.6=r44h3697838_1
  - r-s7=0.2.0=r44h54b55ab_1
  - r-scales=1.4.0=r44hc72bb7e_1
  - r-vctrs=0.6.5=r44h3697838_2
  - r-viridislite=0.4.2=r44hc72bb7e_3
  - r-withr=3.0.2=r44hc72bb7e_1
  - ragtag=2.1.0=pyhb7b1952_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.5=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_1
  - rpds-py=0.27.1=py311h902ca64_1
  - ruamel.yaml=0.18.15=py311h49ec1c0_1
  - ruamel.yaml.clib=0.2.12=py311h49ec1c0_1
  - samtools=1.22.1=h96c455f_0
  - scikit-learn=1.2.2=py311hc009520_2
  - scipy=1.16.2=py311h1e13796_0
  - scorpio=0.3.19=pyhdfd78af_0
  - sed=4.9=h6688a6e_0
  - seqkit=2.10.1=he881be0_0
  - setuptools=80.1.0=pyhff2d567_0
  - sickle-trim=1.33=h577a1d6_12
  - simdjson=3.13.0=h84d6215_0
  - six=1.17.0=pyhe01879c_1
  - skesa=2.5.1=h077b44d_2
  - smart_open=7.3.1=pyhcf101f3_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake-minimal=7.32.4=pyhdfd78af_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - stopit=1.1.2=pyhd8ed1ab_1
  - sysroot_linux-64=2.17=h0157908_18
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2020.2=h4bd325d_4
  - tbb-devel=2020.2=h4bd325d_4
  - tgsgapcloser=1.2.1=h6f25541_4
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - toposort=1.10=pyhd8ed1ab_1
  - tornado=6.5.2=py311h49ec1c0_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.3=pyhe01879c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucsc-fatovcf=482=hdc0a859_1
  - unicodedata2=16.0.0=py311h49ec1c0_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - usher=0.6.6=hdd55de9_3
  - varscan=2.4.3=2
  - vcftools=0.1.17=pl5321h077b44d_0
  - wayland=1.24.0=h3e06ad9_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py311h49ec1c0_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yaml-cpp=0.8.0=h3f2d84a_0
  - yte=1.8.1=pyha770c72_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py311haee01d2_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /rs10g_share01/gbt/local/miniforge3/envs/colog_env
